# Config file for BalancedGrindstone.

# Grindstone durability configuration
# The grindstone now behaves like an anvil, and has a chance to be damaged when used.
durability:

  # The amount of damage the grindstone can take before being destroyed.
  # Set to -1 to disable durability.
  maxHits: 3

  # The chance that repairing an item with the grindstone damages it.
  repairChance: 0.1

  # The chance that disenchanting an item with the grindstone damages it.
  disenchantChance: 0.2

  # The message shown to the player using the grindstone, denoting durability.
  message:
    1: 'This grindstone is nearly broken.'
    2: 'This grindstone is damaged.'
    3: 'This grindstone is in good condition.'


# Disenchantment configuration
disenchant:

  # The chance that an enchanted book will be destroyed when disenchanted.
  bookDestroy: 0.5

  # The chance that an enchanted equipment will be destroyed when disenchanted.
  gearDestroy: 0

  # Damage equipment when disenchanting. Can work with gearDestroy.
  gearDamage:

    # The amount of durability to remove.
    percent: 0.3

    # Whether the amount is relative to total durability or current durability.
    # e.g. a Wooden Pickaxe has 20/60 durability. Assume percent is 30%.
    # When true: pickaxe takes 60 * 0.3 = 18 damage.
    # When false: pickaxe takes 20 * 0.3 = 6 damage.
    useMax: true

    # Whether the damage taken can destroy the equipment.
    # If false, equipment will always have at least 1 durability left.
    canDestroy: true

# Repairing configuration
repair:

  # The amount of bonus durability ON TOP of vanilla bonus to give.
  # This is relative to total durability
  # e.g. repairing Wooden Pickaxe gives 60 * 0.15 = 9 extra durability.
  bonusDurability: 0.15