# Config file for BalancedGrindstone.

# Disenchantment configuration
disenchant:

  # The chance that an enchanted book will be destroyed when disenchanted.
  bookDestroy: 0.5

  # Damage equipment when disenchanting. Can work with gearDestroy.
  gearDamage:

    # The amount of durability to remove.
    percent: 0.3

    # Whether the amount is relative to total durability or current durability.
    # e.g. a Wooden Pickaxe has 20/60 durability. Assume percent is 30%.
    # When true: pickaxe takes 60 * 0.3 = 18 damage.
    # When false: pickaxe takes 20 * 0.3 = 6 damage.
    useMax: true

    # Whether the damage taken can destroy the equipment.
    # If false, equipment will always have at least 1 durability left.
    canDestroy: true

# Repairing configuration
repair:

  # The amount of bonus durability ON TOP of vanilla 5% bonus to give.
  # This is relative to total durability
  # e.g. repairing Wooden Pickaxe gives 60 * 0.05 = 9 extra durability, on top of another 9 from vanilla bonus.
  bonusDurability: 0.05